qatrack/api/urls.py
from django.conf.urls import include, url
from rest_framework.authtoken import views as auth_views
from rest_framework.schemas import get_schema_view

from qatrack.api import views

schema_view = get_schema_view(title='QATrack+ API')


urlpatterns = [
    url(r'^$', views.all_api_roots, name="api-root"),
    url(r'^get-token/', auth_views.obtain_auth_token, name="get-token"),
    #    url(r'^authorize/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^attachments/', include('qatrack.api.attachments.urls')),
    url(r'^auth/', include('qatrack.api.auth.urls')),
    url(r'^comments/', include('qatrack.api.comments.urls')),
    url(r'^contenttypes/', include('qatrack.api.contenttypes.urls')),
    url(r'^faults/', include('qatrack.api.faults.urls')),
    url(r'^parts/', include('qatrack.api.parts.urls')),
    url(r'^qa/', include('qatrack.api.qa.urls')),
    url(r'^qc/', include('qatrack.api.qa.urls')),
    url(r'^servicelog/', include('qatrack.api.service_log.urls')),
    url(r'^units/', include('qatrack.api.units.urls')),
    url(r'^schema/$', schema_view),
]

qatrack/parts/urls.py
from django.conf.urls import url

from qatrack.parts import views

urlpatterns = [
    url(r'^parts_searcher$', views.parts_searcher, name='parts_searcher'),
    url(r'^parts_storage_searcher$', views.parts_storage_searcher, name='parts_storage_searcher'),
    url(r'^room_location_searcher$', views.room_location_searcher, name='room_location_searcher'),
    url(r'^$', views.PartsList.as_view(), name='parts_list'),
    url(r'^low-inventory/$', views.LowInventoryPartsList.as_view(), name='low_inventory_parts_list'),
    url(r'^new/$', views.PartUpdateCreate.as_view(), name='part_new'),
    url(r'^edit/(?P<pk>\d+)?/$', views.PartUpdateCreate.as_view(), name='part_edit'),
    url(r'^details/(?P<pk>\d+)?/$', views.PartDetails.as_view(), name='part_details'),
    url(r'^suppliers/$', views.SuppliersList.as_view(), name='suppliers_list'),
    url(r"^suppliers/(?P<pk>[/\d]+)/$", views.SupplierDetails.as_view(), name="supplier_details"),
]

qatrack/qa/urls.py
from django.conf.urls import url

import qatrack.qa.views.admin

from .views import admin, base, charts, perform, review

urlpatterns = [
    # CUSTOM ADMIN PAGES
    # Copy references and tolerances between testlists
    url(
        r'^admin/copy_refs_and_tols/$',
        admin.CopyReferencesAndTolerances(admin.CopyReferencesAndTolerancesForm),
        name="qa_copy_refs_and_tols"
    ),
    url(
        r'^admin/copy_refs_and_tols/gettestlists/(?P<source_unit>[:|\w]+)/(?P<content_type>[:|\w]+)/$',
        qatrack.qa.views.admin.testlist_json,
        name='qa_copy_refs_and_tols_testlist_json'
    ),
    url(r'^admin/export_testpack/$', admin.ExportTestPack.as_view(), name="qa_export_testpack"),
    url(r'^admin/import_testpack/$', admin.ImportTestPack.as_view(), name="qa_import_testpack"),
    url(r'^admin/recurrences/$', admin.recurrence_examples, name="qa_recurrences"),
    url(r"^$", base.UTCList.as_view(), name="all_lists"),

    # view for composite calculations via ajax
    url(r"^composite/$", perform.CompositeCalculation.as_view(), name="composite"),
    url(r"^autosave/$", perform.autosave, name="autosave"),
    url(r"^autosave/load/$", perform.autosave_load, name="autosave_load"),

    # view for uploads via ajax
    url(r"^upload/$", perform.Upload.as_view(), name="upload"),
    url(r"^charts/$", charts.ChartView.as_view(), name="charts"),
    url(r"^charts/export/csv/$", charts.ExportCSVView.as_view(), name="charts_export_csv"),
    url(r"^charts/data/$", charts.BasicChartData.as_view(), name="chart_data"),
    url(r"^charts/control_chart.png$", charts.ControlChartImage.as_view(), name="control_chart"),
    url(r"^charts/data/testlists/$", charts.get_test_lists_for_unit_frequencies, name="charts_testlists"),
    url(r"^charts/data/tests/$", charts.get_tests_for_test_lists, name="charts_tests"),

    # overall program status
    url(r"^review/$", review.Overview.as_view(), name="overview"),
    url(r"^review/overview-user/$", review.Overview.as_view(), name="overview_user"),
    url(r"^review/overview-objects/$", review.OverviewObjects.as_view(), name="overview_objects"),
    url(r"^review/due-dates/$", review.DueDateOverview.as_view(), name="overview_due_dates"),
    url(r"^review/due-dates-user/$", review.DueDateOverviewUser.as_view(), name="overview_due_dates_user"),

    # review utc's
    url(r"^review/all/$", review.UTCReview.as_view(), name="review_all"),
    url(r"^review/yourall/$", review.UTCYourReview.as_view(), name="review_your_all"),
    url(r"^review/utc/(?P<pk>\d+)/$", review.UTCInstances.as_view(), name="review_utc"),
    url(r"^review/frequency/$", review.ChooseFrequencyForReview.as_view(), name="choose_review_frequency"),
    url(
        r"^review/frequency/(?P<frequency>[/\w-]+?)/$", review.UTCFrequencyReview.as_view(), name="review_by_frequency"
    ),
    url(r"^review/unit/$", review.ChooseUnitForReview.as_view(), name="choose_review_unit"),
    url(r"^review/unit/(?P<unit_number>[/\d]+)/$", review.UTCUnitReview.as_view(), name="review_by_unit"),
    url(r"^review/inactive/$", review.InactiveReview.as_view(), name="review_inactive"),
    url(r"^review/yourinactive/$", review.YourInactiveReview.as_view(), name="review_your_inactive"),

    # test list instances
    url(r"^session/details/$", base.TestListInstances.as_view(), name="complete_instances"),
    url(
        r"^session/details(?:/(?P<pk>\d+))?/report/$",
        review.test_list_instance_report,
        name="test_list_instance_report"
    ),
    url(
        r"^session/details(?:/(?P<pk>\d+))?/$",
        review.TestListInstanceDetails.as_view(),
        name="view_test_list_instance"
    ),
    url(
        r"^session/delete(?:/(?P<pk>\d+))?/$",
        review.TestListInstanceDelete.as_view(),
        name="delete_test_list_instance"
    ),
    url(r"^session/review/$", review.Unreviewed.as_view(), name="unreviewed-alt"),
    url(
        r"^session/review(?:(?:/(?P<rtsqa_form>[a-zA-Z0-9-_]+))?(?:/(?P<pk>\d+)))?/$",
        review.ReviewTestListInstance.as_view(),
        name="review_test_list_instance"
    ),
    url(r"^session/review/bulk/$", review.bulk_review, name="qa-bulk-review"),
    url(r"^session/unreviewed/$", review.Unreviewed.as_view(), name="unreviewed"),
    url(r"^session/unreviewed/visible/$", review.UnreviewedVisibleTo.as_view(), name="unreviewed_visible_to"),
    url(r"^session/group/$", review.ChooseGroupVisibleTo.as_view(), name="choose_group_visible"),
    url(
        r"^session/unreviewedbygroup/(?P<group>[/\d]+)/$",
        review.UnreviewedByVisibleToGroup.as_view(),
        name="unreviewed_by_group"
    ),
    url(r"^session/in-progress/$", perform.InProgress.as_view(), name="in_progress"),
    url(r"^session/continue/(?P<pk>\d+)/$", perform.ContinueTestListInstance.as_view(), name="continue_tli"),
    url(r"^session/edit/(?P<pk>\d+)/$", perform.EditTestListInstance.as_view(), name="edit_tli"),
    url(r"^unit/$", perform.ChooseUnit.as_view(), name="choose_unit"),
    url(r"^utc/perform(?:/(?P<pk>\d+))?/$", perform.PerformQA.as_view(), name="perform_qa"),
    url(r"^site/(?P<site>[/\w-]+?)/$", perform.SiteList.as_view(), name="qa_by_site"),
    url(
        r"^unit/(?P<unit_number>[/\d]+)/frequency/(?P<frequency>[/\w-]+?)/$",
        perform.UnitFrequencyList.as_view(),
        name="qa_by_frequency_unit"
    ),
    url(r"^unit/(?P<unit_number>[/\d]+)/$", perform.UnitList.as_view(), name="qa_by_unit"),
    url(
        r"^frequency/(?P<frequency>[/\w-]+)/unit/(?P<unit_number>[/\d]+)/$",
        perform.UnitFrequencyList.as_view(),
        name="qa_by_unit_frequency"
    ),
    url(r"^frequency/(?P<frequency>[/\w-]+?)/$", perform.FrequencyList.as_view(), name="qa_by_frequency"),
    url(r"^tree/category/$", perform.CategoryTree.as_view(), name="qa_category_tree"),
    url(r"^tree/frequency/$", perform.FrequencyTree.as_view(), name="qa_frequency_tree"),
    url(
        r"^category/(?P<category>[/\w-]+)/unit/(?P<unit_number>[/\d]+)/$",
        perform.UnitCategoryList.as_view(),
        name="qa_by_unit_category"
    ),
    url(r"^category/(?P<category>[/\w-]+?)/$", perform.CategoryList.as_view(), name="qa_by_category"),
    url(r"^due-and-overdue/$", perform.DueAndOverdue.as_view(), name="qa_by_overdue"),
]

qatrack/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.templatetags.static import static as static_url
from django.urls import path
from django.views.generic.base import RedirectView
from django.views.i18n import JavaScriptCatalog

from qatrack.qatrack_core import views

admin.autodiscover()


favicon_view = RedirectView.as_view(url=static_url("qatrack_core/img/favicon.ico"), permanent=True)
touch_view = RedirectView.as_view(url=static_url("qatrack_core/img/apple-touch-icon.png"), permanent=True)


class QAToQC(RedirectView):

    permanent = True
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        return "%s/qc/%s" % (settings.FORCE_SCRIPT_NAME or "", kwargs['terms'])


urlpatterns = [
    url(r'^$', views.homepage, name="home"),
    url(r'^400/$', views.handle_400, name="400"),
    url(r'^403/$', views.handle_403, name="403"),
    url(r'^404/$', views.handle_404, name="404"),
    url(r'^500/$', views.handle_500, name="500"),
    url(r'^accounts/', include('qatrack.accounts.urls')),
    url(r'^qa/(?P<terms>.*)$', QAToQC.as_view()),
    url(r'^qc/', include('qatrack.qa.urls')),
    url(r'^reports/', include('qatrack.reports.urls')),
    url(r'^units/', include('qatrack.units.urls')),
    url(r'^core/', include('qatrack.qatrack_core.urls')),
    url(r'^servicelog/', include('qatrack.service_log.urls')),
    url(r'^parts/', include('qatrack.parts.urls')),
    url(r'^faults/', include('qatrack.faults.urls')),
    url(r'^issues/', include('qatrack.issue_tracker.urls')),

    # Uncomment the next line to enable the admin:
    path(r'admin/', admin.site.urls),
    url(r'^favicon\.ico$', favicon_view),
    url(r'^apple-touch-icon\.png$', touch_view),

    # third party
    url(r'^', include('genericdropdown.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    url(r'^api/', include('qatrack.api.urls')),
]

js_info_dict = {
    'packages': ('recurrence', ),
}
urlpatterns += [url(r'^jsi18n/$', JavaScriptCatalog.as_view(), js_info_dict)]

if settings.USE_SQL_REPORTS:
    urlpatterns.append(url(r'^sql-reports/', include('explorer.urls')),)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# error handling views
handler400 = 'qatrack.qatrack_core.views.handle_400'
handler403 = 'qatrack.qatrack_core.views.handle_403'
handler404 = 'qatrack.qatrack_core.views.handle_404'
handler500 = 'qatrack.qatrack_core.views.handle_500'

if settings.DEBUG:  # pragma: nocover
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

qatrack/contacts/models.py
from django.db import models


class Contact(models.Model):
    """basic contact number"""
    name = models.CharField(max_length=256)
    number = models.CharField(max_length=256)
    description = models.TextField()

    def __str__(self):
        return "%s : %s " % (self.name, self.number)

qatrack/reports/models.py
from datetime import time as dt_time

from django.contrib.auth.models import Group, User
from django.db import models
from django.utils.translation import gettext_lazy as _l
from recurrence.fields import RecurrenceField

from qatrack.qatrack_core.fields import JSONField
from qatrack.reports.reports import report_class


class SavedReport(models.Model):

    FORMATS = [('pdf', _l('PDF')), ('xlsx', 'Excel'), ("csv", _l("CSV"))]

    title = models.CharField(max_length=255,)

    report_type = models.CharField(max_length=128)

    report_format = models.CharField(
        max_length=8,
        choices=FORMATS,
        default="pdf",
    )

    include_signature = models.BooleanField(
        verbose_name=_l("Signature"),
        help_text=_l("Signature field at end of PDFs?"),
        default=True,
    )

    filters = JSONField(blank=True, editable=True)

    visible_to = models.ManyToManyField(
        Group,
        help_text=_l("Select groups who will be able to view and run this report. Leave blank to keep it private."),
        blank=True,
    )

    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        editable=False,
        related_name="report_creator",
    )
    modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        editable=False,
        related_name="report_modifier",
    )

    class Meta:
        permissions = (
            ("can_run_reports", _l("Can Run Reports")),
            ("can_create_reports", _l("Can create Reports")),
            ("can_run_sql_reports", _l("Can run SQL Data Reports")),
            ("can_create_sql_reports", _l("Can create SQL Data Reports")),
        )

        ordering = ("title", "created",)

    def get_filter_class(self):
        return report_class(self.report_type).filter_class

    @property
    def base_opts(self):
        return {
            'title': self.title,
            'include_signature': self.include_signature,
            'report_id': self.id,
        }

    def get_report(self, user=None):
        ReportClass = report_class(self.report_type)
        return ReportClass(base_opts=self.base_opts, report_opts=self.filters)

    def get_report_type_display(self):
        return report_class(self.report_type).name

    def render(self, user=None):
        """create in memory file containing rendering of report"""
        report = self.get_report()
        return report.render(self.report_format)

    def __str__(self):
        return "#%d. %s - %s - %s" % (
            self.pk,
            self.title,
            self.get_report_type_display(),
            self.get_report_format_display(),
        )


class ReportNote(models.Model):

    report = models.ForeignKey(SavedReport, on_delete=models.CASCADE)

    heading = models.TextField(
        help_text=_l("Add a heading for this note"),
    )
    content = models.TextField(
        help_text=_l("Add the content of this note"),
        blank=True,
    )


class ReportSchedule(models.Model):

    TIME_CHOICES = [(dt_time(x // 60, x % 60), "%02d:%02d" % (x // 60, x % 60)) for x in range(0, 24 * 60, 15)]

    report = models.OneToOneField(
        SavedReport,
        on_delete=models.CASCADE,
        help_text=_l("Select the report this schedule pertains to"),
        related_name="schedule",
    )

    schedule = RecurrenceField(
        verbose_name=_l("Schedule"),
        help_text=_l("Define the schedule this report should be sent with."),
    )

    time = models.TimeField(
        verbose_name=_l("Time of day"),
        help_text=_l("Set the time of day this report should be sent (00:00-23:59)"),
        choices=TIME_CHOICES
    )

    groups = models.ManyToManyField(
        Group,
        help_text=_l("Select which groups this report should be sent to."),
        blank=True,
        related_name="scheduledreports",
    )

    users = models.ManyToManyField(
        User,
        help_text=_l("Select individual users this report should be sent to."),
        blank=True,
        related_name="scheduledreports",
    )

    emails = models.TextField(
        verbose_name=_l("Extra recipient emails"),
        help_text=_l("Enter a comma separated list of extra emails this report should be sent to"),
        blank=True
    )

    last_sent = models.DateTimeField(null=True, editable=False)

    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        editable=False,
        related_name="reportschedule_creator",
    )
    modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        editable=False,
        related_name="reportschedule_modifier",
    )

    def recipients(self):
        """Gather recipients that are supposed to recieve this report"""

        users = list(self.users.values_list("first_name", "last_name", "email"))
        users += list(self.groups.values_list("user__first_name", "user__last_name", "user__email"))
        users += [("", "", e) for e in self.emails.split(",")]

        recipients = []
        for fn, ln, e in users:

            e = e.strip()

            if fn and ln and e:
                recipients.append('"%s %s"<%s>' % (fn, ln, e))
            elif e:
                recipients.append(e)

        return recipients

qatrack/templates/explorer/base.html
{% extends "site_base.html" %}
{% load static %}
{% load i18n %}

{% block head_title %}{% if query %} - {{ query.title }}{% elif title %} - {{ title }}{% endif %}{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'select2/css/select2.min.css' %}?v={{ VERSION }}" />
    <link rel="stylesheet" href="{% static 'explorer/css/codemirror.min.css' %}" />
    <link rel="stylesheet" href="{% static 'explorer/css/pivot.min.css' %}" />
    <link rel="stylesheet" href="{% static 'c3/css/c3.min.css' %}?v={{VERSION}}" />
    <link rel="stylesheet" href="{% static 'explorer/css/explorer.css' %}" />
    <link rel="stylesheet" href="{% static 'explorer/css/qat-explorer.css' %}?v={{ VERSION }}" />
    <link rel="stylesheet" href="{% static 'qatrack_core/css/sidebar.css' %}?v={{VERSION}}" />
{% endblock extra_css %}

{% block extra_js %}
  <script type="text/javascript">
      queryId = "{% firstof query.id 'new' %}";
      csrfCookieName = "{% firstof csrf_cookie_name 'csrftoken' %}"
  </script>
{% endblock extra_js %}

{% block require_javascript %}
    require(['list', 'explorer', 'codemirror', 'codemirror/mode/sql/sql', 'codemirror/addon/comment/comment'], function(list, explorer, CodeMirror) {
      {% block sql_explorer_scripts %}
      {% endblock %}
    });
{% endblock require_javascript %}

{% block body_class %}sidebar-mini{% endblock body_class %}

{% block main_sidebar %}
<aside class="main-sidebar">
  <section class="sidebar">
    <ul class="sidebar-menu">
      <li class="header">{% trans "Reports Menu" %}</li>
      {% if can_view or can_change %}
      <li class="primary" title="{% trans "Click to run pre-defined reports" %}">
          <a href="{% url "explorer_index" %}">
            <i class="fa fa-play fa-fw" aria-hidden="true"></i>
            {% trans "Saved Reports" %}
          </a>
        </li>
      {% endif %}
      {% if can_change %}
      <li class="primary" title="{% trans "Click to create a new query" %}">
          <a href="{% url "query_create" %}">
            <i class="fa fa-file-text-o fa-fw" aria-hidden="true"></i>
            {% trans "New Query" %}
          </a>
        </li>
        <li class="primary" title="{% trans "Click to run ad-hoc queries" %}">
          <a href="{% url "explorer_playground" %}">
            <i class="fa fa-file-picture-o fa-fw" aria-hidden="true"></i>
            {% trans "Playground" %}
          </a>
        </li>
      {% endif %}
      {% if can_view or can_change %}
        <li class="primary" title="{% trans "Click to view history" %}">
          <a href="{% url "explorer_logs" %}">
            <i class="fa fa-history fa-fw" aria-hidden="true"></i>
            {% trans "History" %}
          </a>
        </li>
      {% endif %}
    </ul>
  </section>
</aside>
{% endblock main_sidebar %}

{% block body %}
  {% block sql_explorer_content_takeover %}
    <div id="wrap" class="wrap">
      <div class="{% block container_class %}container-fluid{% endblock container_class %}">
          <div class="starter-template">
          {% block sql_explorer_content %}{% endblock %}
          </div>
        </div>
    </div>
  {% endblock %}
{% endblock body %}

qatrack/templates/explorer/export_buttons.html
{% for key, name in exporters %}
    {% if query and query.id %}
        {% if query.params %}
          <li><a href="{% url "download_query" query.id %}?format={{ key }}&params={{ query.params_for_url }}">{{ name }}</a></li>
        {% else %}
          <li><a href="{% url "download_query" query.id %}?format={{ key }}">{{ name }}</a></li>
        {% endif %}
    {% else %}
        <li><input type="submit" value="{{ name }}" data-format="{{ key }}" class="download-button btn btn-link" /></li>
    {% endif %}
{% endfor %}

qatrack/templates/explorer/query.html
{% extends "explorer/base.html" %}

{% load explorer_tags %}
{% load i18n %}

{% block head_title %}{% trans "SQL Query" %}{% endblock head_title %}

{% block sql_explorer_content %}
<div class="row">
  <div id="query_area" class="query-area col-md-12">
    <h2>{% if query %}{{ query.title }}{% if shared %}<small>&nbsp;&nbsp;shared</small>{% endif %}{% else %}{% trans "New Query" %}{% endif %}</h2>
    {% if query %}
      <div class="text-right">
        <a href="{% url "explorer_logs" %}?query_id={{ query.id }}"><h2 class="small">{% trans "History" %}</h2></a>
      </div>
    {% endif %}
    {% if message %}
      <div class="alert alert-info">{{ message }}</div>
    {% endif %}
    <div>

    {% if query %}
      <form role="form" class="form-horizontal" action="{% url "query_detail" query.id %}" method="post" id="editor">{% csrf_token %}
    {% else %}
      <form role="form" class="form-horizontal" action="{% url "query_create" %}" method="post" id="editor">{% csrf_token %}
    {% endif %}

        {% if error %}
          <div class="alert alert-danger">{{ error|escape }}</div>
        {% endif %}

        {{ form.non_field_errors }}

        <div class="form-group">
          {% if form.title.errors %}{% for error in form.title.errors %}
            <div class="alert alert-danger">{{ error|escape }}</div>
          {% endfor %}{% endif %}
          <label for="id_title" class="col-sm-2 control-label">{% trans "Title" %}</label>
          <div class="col-sm-10">
            <input class="form-control" id="id_title" maxlength="255" name="title" type="text" {% if not can_change %}disabled{% endif %} value="{{ form.title.value|default_if_none:"" }}" />
          </div>

        {% if form.connections|length > 1 and can_change %}
          </div>
          <div class="form-group">
            <label for="id_connection" class="col-sm-2 control-label">Connection</label>
            <div class="col-sm-10">
              {{ form.connection }}
            </div>
        {% else %}
          {# still need to submit the connection, just hide the UI element #}
          <div class="hidden">
            {{ form.connection }}
          </div>
        {% endif %}
        </div>

        <div class="form-group">
          {% if form.description.errors %}
            <div class="alert alert-danger">{{ form.description.errors }}</div>
          {% endif %}
          <label for="id_description" class="col-sm-2 control-label">{% trans "Description" %}</label>
          <div class="col-sm-10">
            <textarea class="form-control" cols="40" id="id_description" name="description" {% if not can_change %}disabled{% endif %} rows="2">{{ form.description.value|default_if_none:"" }}</textarea>
          </div>
        </div>

          <input type="hidden" id="id_created_by_user" name="created_by_user" value="{{ form.created_by_user_email }}" />
          {% if form.sql.errors %}
            {% for error in form.sql.errors %}
              <div class="alert alert-danger">{{ error|escape }}</div>
            {% endfor %}
          {% endif %}

          <div class="panel panel-default sql-panel">
            <div class="panel-heading">
              <div class="row">
                <div class="col-md-6">
                  <span class="panel-title">{% trans "SQL" %}</span>
                </div>
                <div class="col-md-6 text-right">
                  {% if query and can_change %}
                  <small><a href="#" title="{% trans "Open in playground" %}" id="playground_button"><i class="glyphicon glyphicon-new-window"></i></a></small>
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="panel-content">
              {% if params %}
                {% include 'explorer/params.html' %}
              {% endif %}
              <textarea class="form-control" {% if not can_change %} readonly disabled {% endif %} cols="40" id="id_sql" name="sql" rows="1">{{ form.sql.value|default_if_none:"" }}</textarea>
            </div>
          </div>

          <div class="form-group">
            <div class="text-center">
              {% if can_change %}
                <div class="btn-group">
                  <input type="submit" value="Save & Run" class="btn btn-default" id="save_button" />
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">{% trans "Toggle Dropdown" %}</span>
                  </button>
                  <ul class="dropdown-menu">
                    {% export_buttons query %}
                    <li role="separator" class="divider"></li>
                    <li><input type="submit" value="Save Only" class="btn btn-link" id="save_only"/></li>
                  </ul>
                </div>
                <button type="button" class="btn btn-default" id="show_schema_button">{% trans "Show Schema" %}</button>
                <button type="button" class="btn btn-default" id="hide_schema_button" style="display: none;">{% trans "Hide Schema" %}</button>
                <button type="button" class="btn btn-default" id="format_button">Format</button>
              {% else %}
                <input type="submit" value="Refresh" class="btn btn-default" id="refresh_button" />
                <div class="btn-group">
                  <label class="btn btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Download" %}</label>
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">{% trans "Toggle Dropdown" %}</span>
                  </button>
                  <ul class="dropdown-menu">
                    {% export_buttons query %}
                  </ul>
                </div>
              {% endif %}
            </div>
          </div>
      </form>
      {% include 'explorer/preview_pane.html' %}
      <div class="row">
        <div class="col-md-6">
          {% if query and can_change and tasks_enabled %}
          {{ form.snapshot }} {% trans "Snapshot" %}
          {% endif %}
        </div>
        <div class="col-md-6 text-right">
          <small>
            {% if query.avg_duration %}
              {% blocktrans with query_avg_duration=query.avg_duration|floatformat:2 user_email=form.created_by_user_email created_time=form.created_at_time %}
                Avg. execution: {{ query_avg_duration }}ms. Query created by {{ created_by_user_email }} on {{ created_time }}.
              {% endblocktrans %}
            {% endif %}
          </small>
        </div>
      </div>
    </div>
  </div>


  <div id="schema" style="display: none;">
    <iframe src="" height="665px" style="border: 1px solid #CCC;" frameBorder="0" id="schema_frame"></iframe>
  </div>

</div>

{% endblock %}

{% block sql_explorer_scripts %}
    var e = new explorer.ExplorerEditor(queryId);
{% endblock %}