qatrack/api/service_log/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from qatrack.api.service_log import views

router = routers.DefaultRouter()
router.register(r'serviceareas', views.ServiceAreaViewSet)
router.register(r'unitserviceareas', views.UnitServiceAreaViewSet)
router.register(r'servicetypes', views.ServiceTypeViewSet)
router.register(r'serviceeventstatus', views.ServiceEventStatusViewSet)
router.register(r'serviceevents', views.ServiceEventViewSet)
router.register(r'thirdparty', views.ThirdPartyViewSet)
router.register(r'hours', views.HoursViewSet)
router.register(r'returntoserviceqa', views.ReturnToServiceQAViewSet)
router.register(r'grouplinker', views.GroupLinkerViewSet)
router.register(r'grouplinkerinstance', views.GroupLinkerInstanceViewSet)

urlpatterns = [
    url(r"^searcher/service_event/$", views.service_event_searcher, name='service_event_searcher'),
    url(r'^', include(router.urls)),
]

qatrack/service_log/urls.py
from django.conf.urls import url

from qatrack.service_log import views

urlpatterns = [
    url(r"^$", views.SLDashboard.as_view(), name="sl_dash"),
    url(r'^event/$', views.ServiceEventsBaseList.as_view(), name="sl_list_all"),
    url(r'^event/create/$', views.CreateServiceEvent.as_view(), name='sl_new'),
    url(r'^event/create/choose-unit/$', views.ChooseUnitForNewSE.as_view(), name="sl_unit_new"),
    url(r'^event/edit(?:/(?P<pk>\d+))?/$', views.UpdateServiceEvent.as_view(), name="sl_edit"),
    url(r'^event/details(?:/(?P<pk>\d+))?/$', views.DetailsServiceEvent.as_view(), name="sl_details"),
    url(r'^event/delete(?:/(?P<pk>\d+))?/$', views.DeleteServiceEvent.as_view(), name='se_delete'),
    url(r'^event/review-required/$', views.ServiceEventsReviewRequiredList.as_view(), name="sl_list_review_required"),
    url(r'^event/review/choose-unit/$', views.ChooseUnitForViewSE.as_view(), name="sl_unit_view_se"),
    url(r'^event/unit/(?P<unit_number>\d+)/$', views.ServiceEventsByUnitList.as_view(), name="sl_list_by_unit"),
    url(r'^event/initiated-by/(?P<tli_pk>\d+)/$', views.ServiceEventsInitiatedByList.as_view(), name="sl_list_initiated_by"),
    url(r'^event/return-to-service-for/(?P<tli_pk>\d+)/$', views.ServiceEventsReturnToServiceForList.as_view(), name="sl_list_return_to_service_for"),
    url(r'^event/status/(?P<pk>\d+)/$', views.ServiceEventsByStatusList.as_view(), name="sl_list_by_status"),
    url(r'^event/report/(?P<pk>\d+)/$', views.service_log_report, name="sl_service_event_report"),
    url(r'^rtsqa/$', views.ReturnToServiceQABaseList.as_view(), name="rtsqa_list_all"),
    url(r'^rtsqa/incomplete/$', views.ReturnToServiceQAIncompleteList.as_view(), name="rtsqa_list_incomplete"),
    url(r'^rtsqa/unreviewed/$', views.ReturnToServiceQAUnreviewedList.as_view(), name="rtsqa_list_unreviewed"),
    url(r'^rtsqa/event/(?P<se_pk>\d+)$', views.ReturnToServiceQAForEventList.as_view(), name="rtsqa_list_for_event"),
    url(r'^se-searcher/$', views.se_searcher, name="se_searcher"),
    url(r'^tli-select(?:/(?P<pk>\d+))?(?:/(?P<form>[a-zA-Z0-9-_]+)/)?$', views.TLISelect.as_view(), name="tli_select"),
    url(r'^tli-statuses/$', views.tli_statuses, name="tli_statuses"),
    url(r'^unit-sa_utc/$', views.unit_sa_utc, name="unit_sa_utc"),
    url(r'^err/$', views.ErrorView.as_view(), name='err'),
    url(r'^down-time/$', views.ServiceEventDownTimesList.as_view(), name='se_down_time'),
    url(r'^handle-unit-down-time/$', views.handle_unit_down_time, name='handle_unit_down_time'),
    url(r'^templates/create_ajax/$', views.CreateServiceEventTemplateAjax.as_view(), name='create_se_template'),
    url(r'^templates/searcher/$', views.service_event_template_searcher, name='se_template_searcher'),
    url(r'^event/schedule/all/$', views.ServiceEventScheduleList.as_view(), name='se_schedule_list_all'),
    url(r'^event/schedule/due-and-overdue/$', views.DueAndOverdue.as_view(), name='se_schedule_due'),
    url(r'^event/schedule/due-dates/$', views.DueDateOverview.as_view(), name='se_schedule_overview_due_dates'),
    url(r'^event/schedule/due-dates-user/$', views.DueDateOverview.as_view(), name='se_schedule_overview_due_dates_user'),
]

qatrack/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.templatetags.static import static as static_url
from django.urls import path
from django.views.generic.base import RedirectView
from django.views.i18n import JavaScriptCatalog

from qatrack.qatrack_core import views

admin.autodiscover()


favicon_view = RedirectView.as_view(url=static_url("qatrack_core/img/favicon.ico"), permanent=True)
touch_view = RedirectView.as_view(url=static_url("qatrack_core/img/apple-touch-icon.png"), permanent=True)


class QAToQC(RedirectView):

    permanent = True
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        return "%s/qc/%s" % (settings.FORCE_SCRIPT_NAME or "", kwargs['terms'])


urlpatterns = [
    url(r'^$', views.homepage, name="home"),
    url(r'^400/$', views.handle_400, name="400"),
    url(r'^403/$', views.handle_403, name="403"),
    url(r'^404/$', views.handle_404, name="404"),
    url(r'^500/$', views.handle_500, name="500"),
    url(r'^accounts/', include('qatrack.accounts.urls')),
    url(r'^qa/(?P<terms>.*)$', QAToQC.as_view()),
    url(r'^qc/', include('qatrack.qa.urls')),
    url(r'^reports/', include('qatrack.reports.urls')),
    url(r'^units/', include('qatrack.units.urls')),
    url(r'^core/', include('qatrack.qatrack_core.urls')),
    url(r'^servicelog/', include('qatrack.service_log.urls')),
    url(r'^parts/', include('qatrack.parts.urls')),
    url(r'^faults/', include('qatrack.faults.urls')),
    url(r'^issues/', include('qatrack.issue_tracker.urls')),

    # Uncomment the next line to enable the admin:
    path(r'admin/', admin.site.urls),
    url(r'^favicon\.ico$', favicon_view),
    url(r'^apple-touch-icon\.png$', touch_view),

    # third party
    url(r'^', include('genericdropdown.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^admin/dynamic_raw_id/', include('dynamic_raw_id.urls')),
    url(r'^api/', include('qatrack.api.urls')),
]

js_info_dict = {
    'packages': ('recurrence', ),
}
urlpatterns += [url(r'^jsi18n/$', JavaScriptCatalog.as_view(), js_info_dict)]

if settings.USE_SQL_REPORTS:
    urlpatterns.append(url(r'^sql-reports/', include('explorer.urls')),)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# error handling views
handler400 = 'qatrack.qatrack_core.views.handle_400'
handler403 = 'qatrack.qatrack_core.views.handle_403'
handler404 = 'qatrack.qatrack_core.views.handle_404'
handler500 = 'qatrack.qatrack_core.views.handle_500'

if settings.DEBUG:  # pragma: nocover
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

qatrack/service_log/models.py
import json
import re

from django.conf import settings
from django.contrib.auth.models import Group, User
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import pre_save
from django.db.utils import IntegrityError
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _l

from qatrack.qa import models as q_models
from qatrack.qatrack_core.fields import JSONField
from qatrack.qatrack_core.scheduling import SchedulingMixin
from qatrack.units.models import NameNaturalKeyManager, Unit, Vendor

re_255 = '([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
color_re = re.compile(r'^rgba\(' + re_255 + ',' + re_255 + ',' + re_255 + r',(0(\.[0-9][0-9]?)?|1)\)$')
validate_color = RegexValidator(color_re, _l('Enter a valid color.'), 'invalid')

NEW_SERVICE_EVENT = 'new_se'
MODIFIED_SERVICE_EVENT = 'mod_se'
STATUS_SERVICE_EVENT = 'stat_se'
CHANGED_RTSQA = 'rtsqa'
PERFORMED_RTS = 'perf_rts'
APPROVED_RTS = 'app_rts'
DELETED_SERVICE_EVENT = 'del_se'

LOG_TYPES = (
    (NEW_SERVICE_EVENT, 'New Service Event'),
    (MODIFIED_SERVICE_EVENT, 'Modified Service Event'),
    (STATUS_SERVICE_EVENT, 'Service Event Status Changed'),
    (CHANGED_RTSQA, 'Changed Return To Service'),
    (PERFORMED_RTS, 'Performed Return To Service'),
    (APPROVED_RTS, 'Approved Return To Service'),
    (DELETED_SERVICE_EVENT, 'Deleted Service Event')
)


class ServiceArea(models.Model):

    name = models.CharField(
        _l("name"),
        max_length=32,
        unique=True,
        help_text=_l('Enter a short name for this service area'),
    )
    units = models.ManyToManyField(
        Unit,
        through='UnitServiceArea',
        related_name='service_areas',
        verbose_name=_l("units"),
    )

    class Meta:
        ordering = ("name",)
        verbose_name = _l('service area')
        verbose_name_plural = _l('service area')

    def natural_key(self):
        return (self.name,)

    def __str__(self):
        return self.name


class UnitServiceArea(models.Model):

    unit = models.ForeignKey(
        Unit,
        on_delete=models.CASCADE,
        verbose_name=_l("unit"),
    )
    service_area = models.ForeignKey(
        ServiceArea,
        on_delete=models.CASCADE,
        verbose_name=_l("service area"),
    )

    notes = models.TextField(
        _l("notes"),
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = _l('unit service area')
        verbose_name_plural = _l('unit service area memberships')
        unique_together = ('unit', 'service_area',)
        ordering = ('unit', 'service_area')

    def __str__(self):
        return '%s :: %s' % (self.unit.name, self.service_area.name)


class ServiceType(models.Model):

    name = models.CharField(
        _l("name"),
        max_length=32,
        unique=True,
        help_text=_l('Enter a short name for this service type'),
    )
    is_review_required = models.BooleanField(
        _l("is review required"),
        default=True,
        help_text=_l('Enable this flag to disable the "Review Required" checkbox for new Service Events'),
    )
    is_active = models.BooleanField(
        _l("is active"),
        default=True,
        help_text=_l('Set to false if service type is no longer used'),
    )
    description = models.TextField(
        _l("description"),
        max_length=512,
        help_text=_l('Give a brief description of this service type'),
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = _l('service type')
        verbose_name_plural = _l('service types')

    def natural_key(self):
        return (self.name,)

    def __str__(self):
        return self.name


class ServiceEventStatus(models.Model):

    name = models.CharField(
        _l("name"),
        max_length=32,
        unique=True,
        help_text=_l('Enter a short name for this service status'),
    )
    is_default = models.BooleanField(
        _l("is default"),
        default=False,
        help_text=_l(
            'Is this the default status for all service events? If set to true every other service event '
            'status will be set to false'
        )
    )
    is_review_required = models.BooleanField(
        _l("is review required"),
        default=True,
        help_text=_l('Do service events with this status require review?'),
    )
    rts_qa_must_be_reviewed = models.BooleanField(
        _l("Return To Service (RTS) QC Must be Reviewed"),
        default=True,
        help_text=_l(
            'Service events with Return To Service (RTS) QC that has not been reviewed '
            'can not have this status selected if set to true.'
        ),
    )
    description = models.TextField(
        _l("description"),
        max_length=512,
        help_text=_l('Give a brief description of this service event status'),
        null=True,
        blank=True,
    )
    colour = models.CharField(
        _l("colour"),
        default=settings.DEFAULT_COLOURS[0],
        max_length=22,
        validators=[validate_color],
        help_text=_l("Choose a colour for this service event status"),
    )
    order = models.PositiveIntegerField(
        _l("Order"),
        help_text=_l("Choose what ordering this status will be listed as in drop down controls"),
        default=0,
    )

    objects = NameNaturalKeyManager()

    class Meta:
        verbose_name = _l('service event status')
        verbose_name_plural = _l('service event statuses')
        ordering = ("order", "pk")

    def save(self, *args, **kwargs):
        if self.is_default:
            try:
                temp = ServiceEventStatus.objects.get(is_default=True)
                if self != temp:
                    temp.is_default = False
                    temp.save()
            except ServiceEventStatus.DoesNotExist:
                pass
        super(ServiceEventStatus, self).save(*args, **kwargs)

    def natural_key(self):
        return (self.name,)

    def __str__(self):
        return self.name

    @staticmethod
    def get_default():
        try:
            default = ServiceEventStatus.objects.get(is_default=True)
        except ServiceEventStatus.DoesNotExist:
            return None
        return default

    @staticmethod
    def get_colour_dict():
        return {ses.id: ses.colour for ses in ServiceEventStatus.objects.all()}


class ServiceEventManager(models.Manager):

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(is_active=True)

    def get_deleted(self):
        return self.get_queryset().filter(is_active=False)

    def review_required(self):
        return self.get_queryset().filter(
            service_status__in=ServiceEventStatus.objects.filter(is_review_required=True),
            is_review_required=True,
        )

    def review_required_count(self):
        return self.review_required().count()


class ServiceEvent(models.Model):

    unit_service_area = models.ForeignKey(
        UnitServiceArea,
        on_delete=models.PROTECT,
        verbose_name=_l("unit service area"),
    )
    service_type = models.ForeignKey(
        ServiceType,
        on_delete=models.PROTECT,
        verbose_name=_l("service type"),
    )
    service_event_related = models.ManyToManyField(
        'self',
        symmetrical=True,
        blank=True,
        verbose_name=_l('related service events'),
        help_text=_l('Enter the service event IDs of any related service events.')
    )
    service_status = models.ForeignKey(
        ServiceEventStatus,
        verbose_name=_l('status'),
        on_delete=models.PROTECT,
        help_text=_l("The current status of this service event"),
    )

    user_status_changed_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name='+',
        on_delete=models.PROTECT,
        verbose_name=_l("status last changed by")
    )
    user_created_by = models.ForeignKey(
        User,
        related_name='+',
        on_delete=models.PROTECT,
        verbose_name=_l("created by"),
    )
    user_modified_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name='+',
        on_delete=models.PROTECT,
        verbose_name=_l("modified by"),
    )
    test_list_instance_initiated_by = models.ForeignKey(
        q_models.TestListInstance,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='serviceevents_initiated',
        verbose_name=_l("initiating test list instance"),
    )
    service_event_template = models.ForeignKey(
        'ServiceEventTemplate',
        blank=True,
        null=True,
        on_delete=models.PROTECT,
        verbose_name=_l("service event template"),
    )
    service_event_schedule = models.ForeignKey(
        'ServiceEventSchedule',
        blank=True,
        null=True,
        on_delete=models.PROTECT,
        verbose_name=_l("service event schedule"),
    )
    due_date = models.DateTimeField(
        null=True,
        blank=True,
        help_text=_l('When was this service event due when it was performed'),
    )

    include_for_scheduling = models.BooleanField(
        help_text=_l("Should this instance be considered when calculating due dates?"),
        default=True,
    )

    datetime_status_changed = models.DateTimeField(
        _l("status changed"),
        null=True,
        blank=True,
    )
    datetime_created = models.DateTimeField(
        _l("created"),
    )
    datetime_service = models.DateTimeField(
        verbose_name=_l('Date and time'), help_text=_l('Date and time service performed')
    )
    datetime_modified = models.DateTimeField(
        _l("modified"),
        null=True,
        blank=True,
    )

    safety_precautions = models.TextField(
        _l("safety precautions"),
        null=True,

qatrack/service_log/templates/service_log/log_rtsqa.html
{% load i18n %}

<li class="rtsqa_log" {% if not show_rtsqa %}style="display: none;"{% endif %}>

  <i class="fa fa-pencil-square-o fa-lg"></i>

  <div class="timeline-item{% if can_view %} can-view{% elif not instance.service_event.is_active %} deleted{% endif %}">

    <span class="time"><i class="fa fa-clock-o"></i>&nbsp;{{ datetime_display }}</span>

    <h3 class="timeline-header header-se_new"{% if can_view %} onclick="window.location='{% url 'sl_details' pk=instance.service_event.id %}'"{% endif %}>
      <div class="pull-right margin-right-20 label label-default">
          {{ instance.service_event.unit_service_area.unit.name }}
      </div>
      <div class="margin-bottom-10">
        {% blocktrans with service_event_id=instance.service_event_id %}
          {{ user }} changed return to service required for service event {{ service_event_id }}
        {% endblocktrans %}
        {% if not instance.service_event.is_active %}<i> ({% trans "deleted" %})</i>{% endif %}</div>
      <div>
        <div class="padding-left-10">
          {% if extra_info|length > 0 %}
            <div class="dash-change title row">
              <div class="col-xs-4">{% trans "Test List Name" %}</div>
              <div class="col-xs-4">{% trans "Session Details" %}</div>
            </div>
            {% for changed in extra_info %}
              <div class="dash-change item rtsqa-row row hover {{ changed.state }}">
                <div class="col-sm-4 tli-name">{{ changed.details }}</div>
                {% if changed.state == 'tli_req_review' %}
                    <div class="col-sm-4">
                      <div class="complete">{% trans "Performed" %}</div>
                        <div class="incomplete">-----</div>
                    </div>
                {% elif changed.state == 'tli_incomplete' %}
                    <div class="col-sm-4">
                        <div class="incomplete">-----</div>
                        <div class="incomplete">-----</div>
                    </div>
                {% elif changed.state == 'tli_reviewed' %}
                    <div class="col-sm-4">
                      <div class="complete">{% trans "Performed" %}</div>
                      <div class="complete">{% trans "Reviewed" %}</div>
                    </div>
                {% elif changed.state == 'deleted' %}
                <div class="col-sm-4"><div class="del">{% trans "Deleted" %}</div></div>
                {% endif %}
              </div>
            {% endfor %}
          {% else %}
            <div class="dash-change title row">
              <div class="col-xs-4">{% trans "All Deleted" %}</div>
            </div>
          {% endif %}
        </div>
      </div>
    </h3>
  </div>
</li>

qatrack/service_log/templates/service_log/log_service_event_deleted.html
{% load i18n %}

<li class="se_log" style="display: list-item;">

  <i class="fa fa-stack">
    <i class="fa fa-wrench fa-stack-custom-main fa-lg"></i>
    <i class="fa fa-times fa-stack-custom-sub upper-left danger"></i>
  </i>

  <div class="timeline-item deleted">
    <span class="time"><i class="fa fa-clock-o"></i>&nbsp;{{ datetime_display }}</span>
    <h3 class="timeline-header header-se_del">
      <div class="pull-right margin-right-20 label label-default">
          {{ instance.service_event.unit_service_area.unit.name }}
      </div>
      <div class="margin-bottom-10">
        {% blocktrans with service_event_id=instance.service_event_id %}
          {{ user }} deleted service event {{ service_event_id }}
        {% endblocktrans %}
      </div>
      <div class="padding-left-10">

        <div class="dash-change title row">
          <div class="col-xs-3">{% trans "Reason" %}</div>
          <div class="col-xs-9">{% trans "Comment" %}</div>
        </div>

        <div class="dash-change item row">
          <div class="col-xs-3">{{ extra_info.reason }}</div>
          <div class="col-xs-9">{{ extra_info.comment }}</div>
        </div>
      </div>
    </h3>
  </div>
</li>

qatrack/service_log/templates/service_log/log_service_event_modified.html
{% load i18n %}

<li class="se_log" style="display: list-item;">

  <i class="fa fa-stack">
    <i class="fa fa-wrench fa-stack-custom-main fa-lg"></i>
    <i class="fa fa-pencil fa-stack-custom-sub fa-flip-horizontal upper-left primary"></i>
  </i>

  <div class="timeline-item{% if can_view %} can-view{% elif not instance.service_event.is_active %} deleted{% endif %}">
    <span class="time"><i class="fa fa-clock-o"></i>&nbsp;{{ datetime_display }}</span>
    <h3 class="timeline-header header-se_new"{% if can_view %} onclick="window.location='{% url 'sl_details' pk=instance.service_event.id %}'"{% endif %}>
      <div class="pull-right margin-right-20 label label-default">
          {{ instance.service_event.unit_service_area.unit.name }}
      </div>
      <div class="margin-bottom-10">
        {% blocktrans with username=user service_event_id=instance.service_event_id %}
          {{ username }} modified service event {{ service_event_id }}
        {% endblocktrans %}
      </div>
      <div class="padding-left-10">
        {% if extra_info.items|length > 0 %}
          <div class="dash-change title row">
            <div class="col-xs-2">{% trans "Field Changed" %}</div>
            <div class="col-xs-4">{% trans "Old Value" %}</div>
            <div class="col-xs-4">{% trans "New Value" %}</div>
          </div>
          {% for key, val in extra_info.items %}
            {% if key == 'a_deleted' %}
              <div class="dash-change item row hover deleted">
                <div class="col-xs-2">{% trans "Attachments deleted" %}</div>
                <div class="col-xs-4">
                  {% for d in val.old %}
                    <div class="row">
                      <div class="col-xs-12">{{ d }}</div>
                    </div>
                  {% endfor %}
                </div>
                <div class="col-xs-4"></div>
              </div>
            {% elif key == 'a_added' %}
              <div class="dash-change item row hover">
                <div class="col-xs-2">{% trans "Attachments added" %}</div>
                <div class="col-xs-4"></div>
                <div class="col-xs-4">
                  {% for a in val.new %}
                    <div class="row">
                      <div class="col-xs-12">{{ a }}</div>
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% else %}
              <div class="dash-change item row hover">
                <div class="col-xs-2">{{ key }}</div>
                <div class="col-xs-4">{{ val.old }}</div>
                <div class="col-xs-4">{{ val.new }}</div>
              </div>
            {% endif %}
          {% endfor %}
        {% endif %}
      </div>
    </h3>
  </div>
</li>

qatrack/service_log/templates/service_log/service_event_delete.html
{% extends "service_log/sl_base.html" %}

{% load i18n %}
{% load widget_tweaks %}
{% load qa_tags %}
{% load qatrack_tags %}
{% load comments %}
{% load static %}

{% block head_title %}Service Event{% endblock %}

{% block extra_css %}
  {{ block.super }}
  <link href="{% static "select2/css/select2.min.css" %}?v={{ VERSION }}" rel="stylesheet">
  <link href="{% static "qatrack_core/css/tables.css" %}?v={{ VERSION }}" rel="stylesheet">
  <link href="{% static "qatrack_core/css/custom-select2.css" %}?v={{ VERSION }}" rel="stylesheet">
{% endblock extra_css %}

{% block extra_js %}
{% endblock extra_js %}

{% block require_javascript %}
  require(['sl_se_delete']);
{% endblock require_javascript %}

{% block body %}

<form id="service-event-delete-form" action="" method="post" novalidate>
  {% csrf_token %}
  <div class="max-width-lg">
    <div class="row margin-bottom-15">
      <div class="col-md-3">
        <h4 class="no-margin-top">
          {% blocktrans with service_event_id=serviceevent.id %}
            Delete Service Event {{ service_event_id }}
          {% endblocktrans %}
        </h4>
        {% service_status_label serviceevent.service_status size="14" %}
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="box box-default">
          <div class="box-body">
            <div class="row margin-bottom-15">
              <div class="col-sm-4">
                <div class="form-group {% if form.reason.errors %}has-error{% endif %}" title="{{ form.reason.help_text }}">
                  <div class="col-sm-12">
                    <label for="{{ form.reason.id_for_label }}" class="">
                      <span>{{ form.reason.label }}{% if form.reason.field.required %} *{% endif %}</span>
                      {% if form.reason.help_text %} - <span class="help-block margin-bottom-0 display-inline-block">{{ form.reason.help_text }}</span>{% endif %}
                    </label>
                    {{ form.reason }}
                    {% for e in form.reason.errors %}
                      <div class="col-sm-12 help-block text-center">{{ e }}</div>
                    {% endfor %}
                  </div>
                </div>
              </div>

              <div class="col-sm-8">
                <div class="form-group {% if form.comment.errors %}has-error{% endif %}" title="{{ form.comment.help_text }}">
                  <div class="col-sm-12">
                    <label for="{{ form.comment.id_for_label }}" class="">
                      <span>{{ form.comment.label }}{% if form.comment.field.required %} *{% endif %}</span>
                      {% if form.comment.help_text %} - <span class="help-block margin-bottom-0 display-inline-block">{{ form.comment.help_text }}</span>{% endif %}
                    </label>
                    {{ form.comment }}
                    {% for e in form.comment.errors %}
                      <div class="col-sm-12 help-block text-center">{{ e }}</div>
                    {% endfor %}
                  </div>
                </div>
              </div>

            </div>

            <div class="row">
              <div class="col-md-12">
                {% if perms.service_log.delete_serviceevent %}
                <div id="submit-delete" class="btn btn-flat btn-danger service-save pull-right">{% trans "Delete" %}</div>
                {% endif %}
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</form>

{% endblock body %}

qatrack/service_log/templates/service_log/service_event_select_widget_option.html
<option value="{{ widget.value|stringformat:'s' }}"{% if widget.disabled %} disabled="disabled"{% endif %}{% if widget.selected %} selected="selected"{% endif %} title="{{ widget.title_html }}">{{ widget.label }}</option>

qatrack/service_log/templates/service_log/service_event_status_label.html
{% load i18n %}

<span class="label smooth-border" style="border-color: {{ colour }}; font-size: {{ size }}px;">{{ name }}</span>

{% if se and perms.service_log.view_serviceevent %}
  <a class="pull-right"
    href="{% url 'sl_details' se.pk %}?next={{ request.path|cut:"data/" }}"
    title="{% trans "Click to view details of this Service Event" %}"
  ><i class="fa fa-search-plus"></i></a>
{% endif %}